services:
  db:
    image: postgres:15-alpine
    container_name: jobpilot_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: jobpilot
    ports:
      - "5432:5432"
    volumes:
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
